version: 2.1

jobs:
  build:
    docker:
       - image: cimg/python:3.8.8

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Install Bandit
      - run:
          name: Install Bandit
          command: |
            pip install bandit

      # Build Docker image
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true  
           
      - run:
          name: Build Docker image
          command: |
            docker build -t your_image_name .

      # Scan Docker image using Trivy
      - run:
          name: Scan Docker image with Trivy
          command: |
            docker run --rm -v /var/run/docker.sock:/var/run/docker.sock aquasec/trivy your_image_name

      # Run Bandit for security checks on the code
      - run:
          name: Run Bandit
          command: |
            bandit -r . -ll -ii -x venv  # Replace 'venv' with any directories to exclude

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
