version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8  # Choose the appropriate Python version
    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Run Bandit for security checks
      - run:
          name: Run Bandit
          command: |
            bandit -r . -ll -ii -x venv  # Replace 'venv' with any directories to exclude

      # Build Docker image
      - run:
          name: Build Docker image
          command: |
            docker build -t your_image_name .

      # DockerScout container scanning
      - run:
          name: DockerScout scanning
          command: |
            docker run -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd)/Dockerfile:/Dockerfile aquasec/trivy your_image_name

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
