version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.8.8

    steps:
      - checkout

      # Setup remote Docker environment
      - setup_remote_docker:
          version: 20.10.14
          docker_layer_caching: true

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Install Bandit
      - run:
          name: Install Bandit
          command: |
            pip install bandit
      # Run Bandit for security checks on the code
      - run:
          name: Run Bandit
          command: |
            bandit -r . -ll -ii -x venv  # Replace 'venv' with any directories to exclude
      # Install Trivy
      - run:
          name: Install Trivy
          command: |
            wget -qO - https://aquasecurity.github.io/trivy-repo/deb/public.key | sudo apt-key add -
            echo "deb https://aquasecurity.github.io/trivy-repo/deb $(lsb_release -sc) main" | sudo tee -a /etc/apt/sources.list.d/trivy.list
            sudo apt-get update && sudo apt-get install trivy

      # Build Docker image
      - run:
          name: Build Docker image and Scan using Trivy
          command: |
            docker build -t flaskapp  .
            trivy image --exit-code 0 --severity MEDIUM,HIGH flaskapp
            trivy image --exit-code 0 --severity CRITICAL flaskapp

            # Login to Docker Hub
      - run:
          name: Login to Docker Hub
          command: |
            echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

      # Push Docker image to Docker Hub
      - run:
          name: Push Docker image to Docker Hub
          command: |
            docker tag flaskapp "$DOCKER_USERNAME"/flaskapp2
            docker push "$DOCKER_USERNAME"/flaskapp2

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
