version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8  # Choose the appropriate Python version
    working_directory: /app

    steps:
      - checkout

      # Install dependencies
      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt

      # Install Bandit
      - run:
          name: Install Bandit
          command: |
            pip install bandit

      # Install Docker
      - run:
          name: Install Docker
          command: |
            sudo apt-get update
            sudo apt-get install -y docker.io  # Adjust for other OS if needed

      # Install DockerScout (Trivy)
      - run:
          name: Install DockerScout (Trivy)
          command: |
            docker pull aquasec/trivy

      # Run Bandit for security checks
      - run:
          name: Run Bandit
          command: |
            bandit -r . -ll -ii -x venv  # Replace 'venv' with any directories to exclude

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
